spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://42.193.169.224:3306/platform-zj?useUnicode=true&characterEncoding=utf-8
    username: judb
    password: ju2009
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    jedis:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 500
#        min-idle: 0
#    timeout: 5000
logging:
#  config: classpath:logback-spring.xml
#  config: classpath:properties/log4j2.xml
#  config: classpath:properties/log4j.properties

mybatis-plus:
  mapper-locations: classpath*:mapping/*.xml
#  configuration:
#    aspect-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    aspect-impl: org.apache.ibatis.logging.log4j2   #Log4j2Impl:这个不在控制台打印查询结果,但是在log4j中打印

