server:
  port: 8100
spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowCredentials: true
            allowedHeaders: '*'
            allowedMethods: '*'
            allowedOrigins: '*'
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: service-auth
          uri: lb://service-auth
          predicates:
            - Path=/auth/**
          filters:
            - RemoveRequestHeader=Expect

        - id: service-edu
          uri: lb://service-edu
          predicates:
            - Path=/edu/**
          filters:
            - RemoveRequestHeader=Expect

        - id: service-ucenter
          uri: lb://service-ucenter
          predicates:
            - Path=/ucenter/**
          filters:
            - RemoveRequestHeader=Expect

        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/order/**
          filters:
            - RemoveRequestHeader=Expect

        - id: service-statistics
          uri: lb://service-statistics
          predicates:
            - Path=/statistics/**
          filters:
            - RemoveRequestHeader=Expect

        - id: service-upload
          uri: lb://service-upload
          predicates:
            - Path=/upload/**
          filters:
            - RemoveRequestHeader=Expect

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8101/auth/rsa/publicKey' #配置RSA的公钥访问地址
feign:
  client:
    config:
      default:
        ConnectTimeOut: 10000
        ReadTimeOut: 10000
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000  #熔断超时时间

ribbon:
  ReadTimeout: 60000  #请求处理的超时时间
  ConnectTimeout: 60000 #请求连接超时时间
  MaxAutoRetries: 0 #对当前实例的重试次数
  MaxAutoRetriesNextServer: 1 #切换实例的重试次数 1


secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/auth/oauth/token"
      - "/auth/rsa/publicKey"
      - "/order/trade/hasbuy/*"
      - "/order/trade/count"
      - "/statistics/daily/register-and-access"
      - "/ucenter/role/by-uid"
      - "/ucenter/member/login"
      - "/ucenter/member/register"
      - "/ucenter/member/login-bg"
      - "/ucenter/member/dashboard-recent-users"
      - "/edu/course/detail/*"
      - "/edu/course-apply/save"
      - "/edu/course-apply/already"
      - "/edu/course/statistics/course/applyCount"
      - "/edu/course/statistics/course/buyCount"
      - "/edu/edu-teacher/bind"
      - "/ucenter/member/info"
      - "/ucenter/role/by-uid"
      - "/edu/course/statistics/course/playCount"
      - "/edu/course/statistics/course/applyCount"
      - "/edu/course/statistics/course/buyCount"
      - "/edu/edu-teacher/clear-bind"
      - "/edu/banner/client-list"
      - "/edu/course/client-list"
      - "/edu/edu-teacher/client-list"
      - "/edu/notice/receive"
      - "/edu/course/client-tree"
      - "/edu/comment/page-client"
      - "/edu/course/list-teacher"
      - "/edu/edu-teacher/info"
      - "/edu/course/page-client"
      - "/edu/subject/list"
      - "/edu/edu-teacher/list"
      - "/ucenter/member/sync-register-login"
      - "/order/alipay"
      - "img"
      - "video"
      - "error"
      - "favicon.ico"
      - "img"
      - "video"
      - "/edu/consult/page-client"
      - "/edu/info/page"
      - "/ucenter/member/sync-users-cache"
      - "/ucenter/config/list"
      - "/edu/info/detail-client/*"
      - "/ucenter/member/picVerifyCode"

